### ISSUE TITLE
Plugins not listed in GNOME software

### ISSUE THREAD

**Issue by TheRsKing** [flathub/org.zrythm.Zrythm#135]
https://flathub.org/apps/org.zrythm.Zrythm While flathub lists the plugins, gnome software does not. Probably because of the different SDK.

**Comment by vchernin** [comment]
In any case this sounds like a gnome software bug. I don’t think we can do anything here to improve gnome software’s plugin detection.

**Comment by TheRsKing** [comment]
> In any case this sounds like a gnome software bug. I don’t think we can do anything here to improve gnome software’s plugin detection.

makes sense, thank you very much for the quick answer
