### ISSUE TITLE
Update the runtime and Zrythm version

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.zrythm.Zrythm#138]
Consider updating the runtime to 47 and Zrythm version to 1.0 (final, not the second rc).

**Comment by vchernin** [comment]
The runtime update should be straightforward. But it is strange we haven’t gotten a bot update for 1.0. Maybe this regex is wrong: https://github.com/flathub/org.zrythm.Zrythm/blob/ff1e975f897f62f0aab85e6ae8550e760afc1e95/org.zrythm.Zrythm.json#L639
